const data = [
  {
    id: 1,
    owner: "Ebhota Jonathan",
    desc: "3 Bedroom House",
    kitchen: "",
    parlor: "",
    diningarea: "",
    masterbedroom: "",
    pic1: "",
    pic2: "",
    pic3: "",
  },
  {
    id: 2,
    owner: "Ebhota Jonathan",
    desc: "3 Bedroom House",
    kitchen: "",
    parlor: "",
    diningarea: "",
    masterbedroom: "",
    pic1: "",
    pic2: "",
    pic3: "",
  },
  {
    id: 3,
    owner: "Ebhota Jonathan",
    desc: "3 Bedroom House",
    kitchen: "",
    parlor: "",
    diningarea: "",
    masterbedroom: "",
    pic1: "",
    pic2: "",
    pic3: "",
  },
  {
    id: 4,
    owner: "Ebhota Jonathan",
    desc: "3 Bedroom House",
    kitchen: "",
    parlor: "",
    diningarea: "",
    masterbedroom: "",
    pic1: "",
    pic2: "",
    pic3: "",
  },
  {
    id: 5,
    owner: "Ebhota Jonathan",
    desc: "3 Bedroom House",
    kitchen: "",
    parlor: "",
    diningarea: "",
    masterbedroom: "",
    pic1: "",
    pic2: "",
    pic3: "",
  },
  {
    id: 6,
    owner: "Ebhota Jonathan",
    desc: "3 Bedroom House",
    kitchen: "",
    parlor: "",
    diningarea: "",
    masterbedroom: "",
    pic1: "",
    pic2: "",
    pic3: "",
  },
  {
    id: 7,
    owner: "Ebhota Jonathan",
    desc: "3 Bedroom House",
    kitchen: "",
    parlor: "",
    diningarea: "",
    masterbedroom: "",
    pic1: "",
    pic2: "",
    pic3: "",
  },
];

export default data;
